### ISSUE TITLE
inconsistent naming conventions

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#163]
The input file naming conventions are a) constantly changing and b) inconsistent.

For example, the baseline experiment says it will use country.csv and world.csv on in baseline.py:34, but the data directory only has country.txt and world.txt. Different versions of the platform may also use different conventions, causing further issues.

We need to a) standardize the ending to input files and b) make the client and server extension agnostic, i.e. it doesn't matter if we get country.txt or country.csv

Also, I have marked this as a bug because it is causing issues for the Cit Lab deployment.

**Comment by rpanah** [comment]
>  country.csv and world.csv on in baseline.py

Those are default input files that aren't used if the scheduler doesn't specify input files. You can remove or change them to `.txt` to avoid confusion, but they aren't used.

> make the client and server extension agnostic

The server and the client (since version 1.5.3) already are file extension-agnostic, and the text files being sent by the server are `.txt` and are used as such (look at `global/scheduler.info` on the server).

**Comment by ben-jones** [comment]
I don't plan on having a long debate about every issue, but I can tell you that this functionality *does not* exist a) in practice or b) in the codebase.

First, the client is not extension agnostic; load_input_file on line 36 of client.py does not do wildcard matching; it directly uses the filename given (in this case, called name). Furthermore, load_input_file is called on any filename given in the experiment parameters (the list containing country.csv from baseline.py:34), per client.py:185. If this fails, then centinel falls back on using <experiment-name>.txt, per client.py:206. What makes you think that this functionality exists on the client?

Second, even if the codebase had this functionality, which it doesn't, we still have the problem that this isn't working in practice. For the future, you might consider asking how this is currently being used or for a way to reproduce the issue, then suggest alternatives. For example, I know that the Citizen Lab is specifying what to run by adding modified country.txt or country.csv files to each users data directory. If you don't like changing country.csv or country.txt, perhaps you could suggest an alternative for sending URL lists, e.g. changing the experiment parameters in the scheduler.info file.

**Comment by rpanah** [comment]
> I don't plan on having a long debate about every issue

So what? We shouldn't discuss things before addressing them? The purpose of the issue tracker is to talk about issues in order to better understand them, which in turn helps us address them better.

> does not do wildcard matching; it directly uses the filename given (in this case, called name).

That's what I was referring to when I said it is extension-agnostic. It just uses the entire filename, in which case it doesn't care what the extension is (hence, 'extension-agnostic'). But it seems like what you mean by it, is that the client look for a file with whatever extension. This functionality isn't there because it limits the input files by disallowing files with the same name but different extensions to be used.

> For the future, you might consider asking how this is currently being used or for a way to reproduce the issue, then suggest alternatives. 

I know what the issue is and I know what files are on the server. I also know how the to reproduce the issue. That's why I didn't ask.

> If you don't like changing country.csv or country.txt

Isn't that literally what I suggested? I also asked you to have a look at the `scheduler.info`. You could decide yourself whether that file needs to be changed according to the file extensions used at the Citizen Lab.

**Comment by ben-jones** [comment]
> So what? We shouldn't discuss things before addressing them? The purpose of the issue tracker is to talk about issues in order to better understand them, which in turn helps us address them better.

Conversations on this issue tracker tend to get drawn out for no reason, which is especially non-productive when we have larger issues to address. There is no point in having conversations in this much depth when we need to decide what we are doing with the platform.

> That's what I was referring to when I said it is extension-agnostic. It just uses the entire filename, in which case it doesn't care what the extension is (hence, 'extension-agnostic'). But it seems like what you mean by it, is that the client look for a file with whatever extension. This functionality isn't there because it limits the input files by disallowing files with the same name but different extensions to be used.

This is not the definition of agnostic; the server code for this project uses my definition (see views.py:250) and [this link](http://whatis.techtarget.com/definition/agnostic) has ~10 examples of the IT field that corroborate my example. Furthermore, (quoting from that article) agnostic means "In IT, that translates to the ability of something to function without “knowing” the underlying details of a system that it is working within". Applied to our example, this means matching any file extension. Why would agnostic mean that it doesn't use an extension? 

There is no basis for your definition and there are counter examples *from our own code*. 

I can't say this more plainly; our code should match files with any extension as long as the basename matches.

> I know what the issue is and I know what files are on the server. I also know how the to reproduce the issue. That's why I didn't ask.

The problem is that the Citizen Lab creates URL lists and these aren't being run on the client. Your comment indicated that the code supported the option I discussed above, but it doesn't. You can't say that you know how to reproduce the issue when you don't know what it is.

> Isn't that literally what I suggested? I also asked you to have a look at the scheduler.info. You could decide yourself whether that file needs to be changed according to the file extensions used at the Citizen Lab.

Telling people to manually edit hundreds of files is not a scalable solution and cannot be applied to a tool that is supposedly almost done. Even if we modify the scheduler.info files, we would need to write code for this admin task. I think this solution speaks volumes about the current state of our code base and the current design philosophy.

**Comment by jakubd** [comment]
I am not sure how global/scheduler.info is helpful as there is no guides about input file names.  This is experiments/global/schedule.info unless you mean another file.

```
{
  "baseline": {
    "frequency": 86400,
    "python_exps": {
      "baseline": {
        "params": {
          "traceroute_methods": [
            "tcp",
            "udp"
          ]
        }
      }
    },
    "last_run": 0
  }
}
```

Here is an example of a client running the latest centinel-dev:

```
$ sudo centinel-dev
2015-08-14 14:55:57,222: INFO: Centinel started.
2015-08-14 14:55:57,224: INFO: Getting metadata for experiment...
2015-08-14 14:56:02,140: INFO: Running baseline...
2015-08-14 14:56:02,142: ERROR: Input file not found /root/.centinel/data/country
2015-08-14 14:56:02,143: ERROR: Input file not found /root/.centinel/data/world
```

Naming input files anything other than "country" and "world" results in this error, including both .txt and .csv.  I will see if I can set up a test pi to replicate the error.

**Comment by sneft** [comment]
To add to Jakub's comment: While renaming the files to 'country' and 'world' will solve the problem and allow for a succesful test, after running centinel-dev --sync it will restore country.csv and world.txt and prevent future runs without renaming again.

**Comment by jakubd** [comment]
Spent some time trying to find out what is going on.  I think the issue stems from [this commit] (https://github.com/iclab/centinel/commit/660c5f52e885f373b007174e7e6e735501a8b660#diff-192e8f1b5649b5354388f8564356b0d5)

On the server side /experiments/global/baseline.py seems out of date as it selects input files according to the pre-commit version:

```python
class BaselineExperiment(Experiment):
    name = "baseline"
    # country-specific, world baseline
    # this can be overridden by the main thread
    input_files = ['country', 'world']

    def __init__(self, input_files):
        self.input_files = input_files
        self.results = []
```

@rpanah @ben-jones  can one of you make sure to update the file so that it is correct?  Or can I just copy in [this file](https://github.com/iclab/centinel/blob/master/centinel/experiments/baseline.py) ?

**Comment by jakubd** [comment]
Went ahead and tested this was the case and the fix was updating /global/experiments/ with the up-to-date version.

Closin'
